### ISSUE TITLE
Concept

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#1]
High level goal: Make coronavirus official information available in English

## Map

A map outlining each prefecture in Japan, showing a count of the # of cases in each.

## Data Table

Below the map, a table with high level info for each case

## Helpful Resources

A list of helpful links, resources, and data sources for the page above.

**Comment by Kay-Cube** [comment]
### Helpful Resources:
**Info from Tokyo Metropolitan Infectious Disease Surveillance Center**
http://idsc.tokyo-eiken.go.jp/diseases/2019-ncov/

**WHO information about the virus**
https://www.who.int/emergencies/diseases/novel-coronavirus-2019

**online course about COVID-19 from WHO**
https://openwho.org/courses/introduction-to-ncov

**medical articles about covid-19 patients**
https://www.medrxiv.org/content/10.1101/2020.02.06.20020974v1
https://www.medrxiv.org/content/10.1101/2020.02.10.20021675v1

**Comment by reustle** [comment]
Load data directly from the source sheet via https://github.com/franciscop/drive-db
