### ISSUE TITLE
Fix Chart Axis Labels

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#107]
- [ ] On the trend chart, the Y axis doesn't have 0 at the bottom for some reason.
- [ ] On the X axis, the far right label is cut off. Can we add some kind of right padding?

Checking [the documentation](https://c3js.org/reference.html) may be helpful

![image](https://user-images.githubusercontent.com/304560/77436241-97094080-6e26-11ea-9dcc-538f05d89c05.png)

**Comment by l15n** [comment]
✋  will send a PR in a bit
