### ISSUE TITLE
Regional/Prefecture-Level trajectories

### ISSUE THREAD

**Issue by l15n** [reustle/covid19japan#109]
I've found that FT's cross-country/region trajectory charts are great for understanding the relative status of pandemic spread.

https://www.ft.com/coronavirus-latest

Example via Twitter:
![](https://pbs.twimg.com/media/ET1FmRRWkAI4QKw?format=jpg&name=small)
https://twitter.com/jburnmurdoch/status/1242225650125193219

I think that adding a graph like this would be especially helpful in Japan because of how reporting and disease tactics are not centralized here. There's a big difference between the prefectures that is quite difficult to grasp with just the latest total figres.

What's needed:

- Prefecture-level daily trend data (cases, not deaths right now)
- Offset the above to an arbitrary starting point, e.g days since N cases
- Convert dates to days since N cases
- Chart with log scale on y-axis

This should be achievable with current data, after some degree of massaging. 

@reustle What do you think? This is something I'm interested in building.

**Comment by liquidx** [comment]
That would be awesome. 

We just started a data repo that has exported the data from the spreadsheet into a JSON file:
https://github.com/reustle/covid19japan-data/tree/master/patient_data

I'm in the middle of automating pulling data from the spreadsheet and checking it in, but at the very least, that JSON file should have the data you need.

**Comment by reustle** [comment]
Thoughts of having the page show country-wide by default, with the option to drill down by prefecture?

KPIs and trend charts would show by prefecture, map would stay the same.

Otherwise, we add some kind of sparkline into the existing prefectures table, and make the height fixed and scrollable (so the table isn't as tall as it is now).

**Comment by l15n** [comment]
As a visitor, will the visualization tell me what I want to know? Does it summarize the data in a useful way? I'm not sure, so I'd like to try building a prototype first to make a concrete comparison.

> Thoughts of having the page show country-wide by default, with the option to drill down by prefecture?

Since the page is getting crowded, I do agree that country-wide should be a priority. However, since global dashboards show Japan's top level numbers anyway, getting a handle on local status is likely to be more helpful for residents.

> KPIs and trend charts would show by prefecture, map would stay the same.
> 
> Otherwise, we add some kind of sparkline into the existing prefectures table, and make the height fixed and scrollable (so the table isn't as tall as it is now).

Do you have a good example? The best one I can think of is the country comparison on [Our World in Data's Corona Virus page](https://ourworldindata.org/coronavirus)

<img width="810" alt="Screen Shot 2020-03-25 at 10 41 19 PM" src="https://user-images.githubusercontent.com/3714/77542602-ca60d380-6ee9-11ea-9179-e90056a0c9e9.png">

I've also started collecting examples of country-level trackers for inspiration:

- US: https://covidtracking.com/data/
- Singapore: https://www.againstcovid19.com/singapore/dashboard
- UK (The Guardian): https://www.theguardian.com/world/2020/mar/25/coronavirus-uk-how-many-confirmed-cases-are-in-your-area

**Comment by liquidx** [comment]
I am very interested in added a sparkline or something like the Our World in Data graph to each prefecture row. It gives you a pretty quick glance of what's really happening.

My branch isn't quite working any more and I've wanted to move most of that fetching from google sheets to a static JSON file, which is now very close to done. So we could start generating the sparkline on the main site.

Here's an example that I had (I don't know where my other example was)

<img width="643" alt="Screen Shot 2020-03-19 at 23 16 53" src="https://user-images.githubusercontent.com/72062/77560756-33a01100-6f01-11ea-849d-18dd8ca3b58d.png">

**Comment by l15n** [comment]
I found another great visualization tied to some new open data sources:

https://www.stopcovid19.jp/

This site illustrates active cases by prefecture vs available hospital bets, classified into a number of types.

Also has some per-prefecture drilldowns: https://www.stopcovid19.jp/tokyo.html

I think #91 was looking for something similar (in terms of active vs recovered)


- Site Source: https://github.com/code4sabae/covid19
    - data as JSON: https://github.com/code4sabae/covid19/tree/master/data
- API Server / scraping source: https://github.com/code4sabae/app_sabae_cc

**Comment by liquidx** [comment]
I got my branch back up and running:
https://covid2019-test.firebaseapp.com/

<img width="746" alt="Screen Shot 2020-03-27 at 0 32 03" src="https://user-images.githubusercontent.com/72062/77665189-ab824000-6fc2-11ea-91f6-8d67f7801428.png">

https://github.com/liquidx/covid19japan/tree/feature/sparkline

**Comment by l15n** [comment]
Another Japan dashboard

**Comment by l15n** [comment]
USA version

http://systrom.com/covid19-charts-us-states/

(It's Kevin!)

**Comment by liquidx** [comment]
I think the data is there now in 
https://github.com/reustle/covid19japan-data

With a little work, you can probably generate a similar graph for Tokyo vs Aichi vs Osaka etc.

**Comment by l15n** [comment]
> With a little work, you can probably generate a similar graph for Tokyo vs Aichi vs Osaka etc.

Great! I'll give it a shot today

**Comment by l15n** [comment]
A first attempt:

![Screen Shot 2020-03-28 at 7 33 01 PM](https://user-images.githubusercontent.com/3714/77821111-f9b25300-712a-11ea-9fcc-5a2b8d4db13d.png)

**Comment by l15n** [comment]
I explored a number of thresholds, but I think that with the current state of the prefectures, using a threshold of n>=50 is best. I expect n>=100 to be best in a few days though.

![Screen Shot 2020-03-28 at 11 22 48 PM](https://user-images.githubusercontent.com/3714/77825374-380c3a00-714c-11ea-9d88-3c6fc6a2557f.png)
![Screen Shot 2020-03-28 at 11 22 03 PM](https://user-images.githubusercontent.com/3714/77825378-3e9ab180-714c-11ea-8111-7a2ebd087786.png)
![Screen Shot 2020-03-28 at 11 23 13 PM](https://user-images.githubusercontent.com/3714/77825381-4195a200-714c-11ea-832d-b92c6749ed27.png)


Currently, I'm using a linear scale since it seems to work best. Log scale doesn't work well yet, suggesting that almost all prefectures don't have exponential growth yet.

**Comment by reustle** [comment]
It's live and looks great! Should we add a clarification for what the number means? I'm guessing it's currently "Days since the 50th case"?

**Comment by l15n** [comment]
Yep, I have an X-axis label that is perhaps a little too easy to miss.

![Screen Shot 2020-03-30 at 1 00 09 PM](https://user-images.githubusercontent.com/3714/77873984-7e65b400-7286-11ea-8a34-4300c1e44d25.png)

Maybe I can reposition the X-axis label and also add a Y-axis label too.
