### ISSUE TITLE
Warning On Todays Data

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#122]
On both the trend line and cases bar chart, the values for `today` are quite low until the end of the day.

Let's add some kind of indicator to the user (greyed out color, tooltip, etc) to make it clear that these are not the final totals for the day. Very open for suggestions on the best way to do this.

**Comment by ann-kilzer** [comment]
Lower the saturation of the color? Use an open circle or a dotted line between today's and yesterday's dot?
