### ISSUE TITLE
add docs to .gitignore

### ISSUE THREAD

**Issue by ann-kilzer** [reustle/covid19japan#127]
I notice that things in the docs folder update based on the npm build. Would be great to have auto-generated items under `.gitignore` and only updated in production builds. 

@reustle

**Comment by reustle** [comment]
This is actually the directory that powers the site. Github Pages takes what is in /docs and deploys that to their webserver. Unless I misunderstand your question, I think we need to keep it 🙏

**Comment by ann-kilzer** [comment]
Ahh got it, so you're using github pages. Understood.
