### ISSUE TITLE
Cosistent Code Formatting

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#128]
We often get PRs that include many code formatting changes, automatically done by peoples code editors. Adding spaces here, removing spaces there, etc.

How can we set a project-wide config file to ensure that everyones editors are not constantly reformatting the code?

**Comment by reustle** [comment]
From @python273:
> Since you already have npm packages, I think it should be easy to add prettier and precommit hook: https://prettier.io/docs/en/precommit.html

**Comment by mertd** [comment]
If Prettier is your formatter of choice, I could create a quick PR to add it. Adding it as a precommit hook is not a feature of Prettier itself, though. Using [Husky](https://github.com/typicode/husky), any command can be set up to run before committing, e.g. `eslint --fix` configured with whatever style you prefer.

**Comment by ann-kilzer** [comment]
Haven't used prettier but heard good things. I've set up eslint a bunch of times too and can help with that.

**Comment by mertd** [comment]
@reustle @ann-kilzer @python273 I opened #131, have a look and see if this is what you imagined
