### ISSUE TITLE
Automate Data Update Checks

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#13]
Crawl the government release pages and notify somehow (via email?) that a new update has been posted.

Sources listed in the readme here: https://github.com/reustle/covid19japan#data-sources

Similar issue: https://github.com/reustle/covid19japan/issues/17

**Comment by brugz** [comment]
It looks like the JSON file served from S3 is used as source-of-truth for rendering the Covid19Japan landing pages. How is the JSON file produced? Is the data just pulled from gSheets and pushed to S3?

**Comment by reustle** [comment]
Every few minutes, this Github Action runs:

https://github.com/reustle/covid19japan/blob/master/.github/workflows/schedule.yml

Which runs this script:

https://github.com/reustle/covid19japan/blob/master/scripts/cache-spreadsheet-data/cache-sheet.js

**Comment by brugz** [comment]
Is the spreadsheet populated manually then, when new data from the government is available?

**Comment by reustle** [comment]
Yes exactly, you can see editors on the sheet currently

**Comment by liquidx** [comment]
This task is somewhat outdated now, closing this for now. We could reopen a new one in the data repo is there ends up being a good way to do this.
