### ISSUE TITLE
Show Last Updated As Time Ago

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#132]
Currently the last updated time looks like:

>  Last Updated: Mar 29 2020, 15:53 JST 

Let's instead show it as:

>  Last updated 28 minutes ago

>  Last updated 3 hours ago

> Last updated 18 hours ago

**Comment by colinthornton** [comment]
It looks like moment has a method for this: https://momentjs.com/docs/#/displaying/fromnow/

I haven't made any contributions yet but I'd like to take this one if possible.

**Comment by Crocsx** [comment]
I think adding moment (that is a huge package) just for this is a bit overkill, you can easily find already made method to do so.

**Comment by Crocsx** [comment]
i found this for exemple, you could make a small file to for utils function 

https://muffinman.io/javascript-time-ago-function/

**Comment by colinthornton** [comment]
@Crocsx I'm in total agreement with you, I just suggested moment cause it's already in the dependency list (I see now that it's not being imported though).

**Comment by reustle** [comment]
Thanks guys. The main concern right now is the formatting of the date source. We need to switch to automatically generated the timestamp from the current manually updated cell, so we can trust that it will parse properly. cc @liquidx

**Comment by colinthornton** [comment]
@reustle As it is now is the `lastUpdated` value guaranteed to be in the format `MMM DD YYYY, HH:mm JST`?
