### ISSUE TITLE
Japanese language alignment

### ISSUE THREAD

**Issue by Kay-Cube** [reustle/covid19japan#133]
@reustle 
Align terms of confirmed patients in Japanese language.

New Cases By Day
陽性者数 (日別) --> 日別新着感染者数

Confirmed Case Trajectories by Prefecture (> 50 Cases)
都道府県別の患者数推移 (50例以上) --> 都道府県別の感染者数推移 (50例以上)

**Comment by reustle** [comment]
@mertd Could you please incorporate this into your translations PR? 🙏

**Comment by mertd** [comment]
@reustle done!
