### ISSUE TITLE
Language switching feels unresponsive

### ISSUE THREAD

**Issue by colinthornton** [reustle/covid19japan#152]
@reustle 
Now that the page has grown in size, the click event handler for swapping languages is taking a perceivable amount of time. On the performance tab in Firefox devtools it measures at nearly two seconds:

![image](https://user-images.githubusercontent.com/17635021/77975075-fc33c900-7333-11ea-8fa3-3dbc6ba759b5.png)

That's not a huge amount of time, but there's currently no feedback to the user to let them know that it's in the middle of loading, so it feels unresponsive.

Off the top of my head I can think of three ways to improve this:
1. Refactor the language switching implementation so it speeds up (#124 related)
2. Make the user aware of the loading by displaying a loading spinner overlay
3. Make the user aware of the loading by linking to a new page (move the languages to different endpoints (e.g. /en /ja), so that the page fully reloads when switching between languages)

**Comment by reustle** [comment]
Thank you. Yes I'd love to get #124 merged but noticed there may be a few rendering issues, still trying to debug locally to make sure it isn't just me (but also tied up with a few other things).

If you are keen to help out, reviewing that PR would be incredibly helpful, and that would get us much closer to being able to refactor / improve language switching overall.

I'm open to the idea of having a separate page for each languages, let's discuss after 124 is merged as I think it will be made much easier w/ that. 🙇

**Comment by mertd** [comment]
This might even be solved by #124 as, at least for me, language switching is almost instantaneous.

**Comment by mertd** [comment]
I just merged the latest changes from master into the branch in #124 and now language switching is just as sluggish. Since the language switching itself did not change, the issue seems to originate elsewhere.

**Comment by l15n** [comment]
![Screen Shot 2020-04-01 at 12 31 21 AM](https://user-images.githubusercontent.com/3714/78044951-4bb7da80-73b0-11ea-839b-4d627dc63a69.png)

The profiler indicates that its because we're redrawing the prefecture table inside the click handler.

https://github.com/reustle/covid19japan/blob/907a66069de091d45550a1155750b14a99c80e82/src/index.js#L1142-L1151

I think we're kind of forced into it because of how the annotations and other text on the charts by c3.js doesn't support localization so we end up redrawing everything. Not sure if it cleans up existing objects first either.

**Comment by reustle** [comment]
Nice detective work. Can we remove annotations within the table charts for now to remove the issue?

**Comment by l15n** [comment]
Another thought is that our current implementation for rendering the charts actually do data pre-processing. It might be worthwhile to separate the chart code from the data munging code, but I don't know if it will make much of a difference if rendering (the purple Recalculate Style / Layout Apply Style Changes) parts are the bottleneck.

> Nice detective work. Can we remove annotations within the table charts for now to remove the issue?

I think the prefecture table is the biggest problem. It's just the Prefecture and Header cells than really need to be redrawn, so if the numbers / charts can be kept as is it should improve.

**Comment by reustle** [comment]
Many years ago (10~?) I used this: https://developers.google.com/chart/image/docs/chart_playground - wonder if there is similar out there, for use cases like this

**Comment by liquidx** [comment]
Agreed.  I noticed that changing languages tries to reload everything which is probably not necessary. It really should just be swapping all the text labels. The table is the only one that doesn't use the data-ja= to store the translations.

If we just make that modification, we can remove the drawPrefectureTable in the switch language function.

**Comment by reustle** [comment]
Agreed, should help in the short term and we'll have to handle it properly in the active lang pr
