### ISSUE TITLE
Error Debugging Support

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#153]
We are using Sentry.io to track errors and have started to see quite a few add up. I would love for any experienced developers to help out in trying to track down the sources of some of these bugs and get them resolved.

I'm not sure what the best way to handle this will be, as I don't want to flood github issues with each of these errors, but can't simply give everyone access to our Sentry account. Let's discuss here.

---

![image](https://user-images.githubusercontent.com/304560/77977317-5afc4100-733a-11ea-8f7f-e22de3e69486.png)

![image](https://user-images.githubusercontent.com/304560/77977433-ab739e80-733a-11ea-9fd1-6275d91f55b0.png)

**Comment by KotaAoyama** [comment]
Hello,
I am a software engineer with experience in JavaScript and Mapbox.
I'd like to help you with the error debugging support.
I'm not sure this is a good way, but if you can, could you invite me as your Sentry team member?

If you can't give someone access to your Sentry account, the other way is ok.

**Comment by reustle** [comment]
@KotaAoyama Thank you! Added you based on the email showing on your github profile
