### ISSUE TITLE
Automate data extraction

### ISSUE THREAD

**Issue by realmonitoro** [reustle/covid19japan#159]
Hello everyone,

I'm the founder of https://monitoro.xyz, and our product automates data extraction from websites when they change and sends it to other services such as Google Sheet which this project seems to be using.

Following a brief exchange with @reustle in HN and via email, I proposed to donate some resources to the project that might be helpful.
I notice a previous conversation in this topic https://github.com/reustle/covid19japan/issues/13. Please let me know if this should be moved there.

The way it would work is basically:
1- Open a webpage from which to extract data (for example the regional status websites)
2- Specify the items to extract (all the relevant fields that you are extracting from that page into the sheet)
3- Hook this up to Google sheet (add a google app script to the sheet to receive the data, and specify to which cell does each monitor send data)

Alternatively, you could just send a change notification instead of extracting data, but you would still need to manually open the website afterwards and copy paste stuff into your sheet.

I'd like to know to which extent this is relevant and useful and if you'd like to proceed.

**Comment by realmonitoro** [comment]
Closing this issue as it doesn't seem of interest to the project.

**Comment by reustle** [comment]
Thanks for the offer! I think the data format is too inconsistent at this time.

**Comment by realmonitoro** [comment]
>  I think the data format is too inconsistent at this time.

I understand. Our offer remains open so feel free to reach out anytime this changes.
