### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#16]
Which license do you suggest?

**Comment by nishad** [comment]
May be some insights from https://choosealicense.com/

**Comment by tagawa** [comment]
My vote is for the [MIT license](https://opensource.org/licenses/MIT) for its simplicity, and that it permits pretty much anything. The only restriction on distribution is including the copyright notice, which seems appropriate for such a project IMO.

**Comment by l15n** [comment]
For the code: MIT 👍 

For the data: CC BY SA?

https://creativecommons.org/licenses/by-sa/4.0/

**Comment by reustle** [comment]
My only ask is that we require a link on their site back to ours (site or repo), if you think it's reasonable. Seeing others fork and use our code has been great, and I want to make sure that can continue to happen:

- https://covidsl.com
- https://covid19kerala.info

**Comment by l15n** [comment]
The Tokyo metropolitan covid 19 site uses the MIT license, but also has an index of forked sites:

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/FORKED_SITES.md

**Comment by tagawa** [comment]
I like the idea of a list of forked sites as an incentive for projects to let us know when code is re-used. Have created a PR with the license addition and code re-use section in README (#155).
