### ISSUE TITLE
Add anchor links to H1 headings

### ISSUE THREAD

**Issue by ann-kilzer** [reustle/covid19japan#161]
Now that the site has many more informative sections, it would be helpful to have some anchor links so that we can share specific parts of the site, e.g. `https://covid19japan.com/#travel-restrictions` 

Thoughts @reustle ?

**Comment by reustle** [comment]
💯 👌 


@Kay-Cube also talked about adding links soon, but I think we'll have a higher level discussion about design soon

**Comment by liquidx** [comment]
After nearly 8 months 🤦🏻‍♂️, this anchor link now works.
