### ISSUE TITLE
Using proportional symbol map instead of choropleth map

### ISSUE THREAD

**Issue by kymok** [reustle/covid19japan#163]
// Please tag @reustle in your newly created issue

Shading administrative regions by case numbers leads to misunderstanding of quantity. Hokkaido, for example, has fewer cases compared to Tokyo while its large area has much larger visual impact. I recommend using proportional symbol map (e.g. circle symbol based on numbers of cases) to avoid misunderstanding.

For further information please refer to:
https://en.wikipedia.org/wiki/Choropleth_map#Normalization

**Comment by reustle** [comment]
Thank you for bringing this up. What do you think about converting to something like this? https://github.com/reustle/covid19japan/issues/27

**Comment by kymok** [comment]
Thank you, it totally makes sense. Sorry for oversighting #27.

**Comment by reustle** [comment]
No worries, thanks!
