### ISSUE TITLE
I made auto scraper for tracking Japan numbers

### ISSUE THREAD

**Issue by wasfy-hatem** [reustle/covid19japan#17]
@reustle 
Hello,
I'm a DevOps Engineer and I live in Tokyo, Japan.
For my personal usage, I started a basic python scraper to automate collecting data about Japan Corona Virus cases.
http://wasfy.ddns.net/corona_virus_tracker.html

I like to share it with you and to help if needed.

Best regards,
Hatem Wasfy

**Comment by reustle** [comment]
Thank you! Where do you get your data? Do you have your code hosted publicly somewhere?

**Comment by wasfy-hatem** [comment]
Hello,

I get data from scraping 'worldmeters' website:

https://www.worldometers.info/coronavirus/


I will push my code to github and share it with you.

Best regards,

Hatem Wasfy

**Comment by reustle** [comment]
Thanks! I think this could be helpful with #13

**Comment by wasfy-hatem** [comment]
@reustle 
You're welcome.
Here is the repository of my back-end code.
https://github.com/wasfy-hatem/automatic_corona_virus_tracker

**Comment by brugz** [comment]
Looks like the repo is 404'ing -- did this get moved?

**Comment by reustle** [comment]
He only shared it with me directly.

**Comment by reustle** [comment]
Merging this into #13
