### ISSUE TITLE
Charts showing future data

### ISSUE THREAD

**Issue by tagawa** [reustle/covid19japan#171]
Today (April 2nd) the Outbreak Spread Trend and New Cases charts are showing provisional figures for tomorrow (April 3rd). Shouldn't the provisional figures be for the remainder of today?

<img width="1105" alt="Screen Shot 2020-04-02 at 17 00 59" src="https://user-images.githubusercontent.com/94173/78224712-f8ef3780-7503-11ea-829e-1ca077e4df60.png">

cc @reustle

**Comment by reustle** [comment]
Strange, is it still happening? It may have been a temporary data issue. Thanks for reporting

**Comment by tagawa** [comment]
Looks like it's fixed now - thanks.
