### ISSUE TITLE
Include daily increase in Confirmed Case Trajectories by Prefecture

### ISSUE THREAD

**Issue by colinthornton** [reustle/covid19japan#182]
@reustle @l15n 

The Outbreak Spread Trend chart includes the total cases as well as the daily increase, e.g. `1142 (+40)`.
![image](https://user-images.githubusercontent.com/17635021/78316522-d9efb480-759a-11ea-8313-16b3803630e8.png)

It would be nice if the Confirmed Case Trajectories by Prefecture chart displayed similarly by including the daily increase.
![image](https://user-images.githubusercontent.com/17635021/78316698-479be080-759b-11ea-9987-1e79ef9470cd.png)

**Comment by colinthornton** [comment]
I saw lots of news about Tokyo having 97 new cases yesterday, so I wanted to compare our numbers.

**Comment by l15n** [comment]
Good idea! I'll see if I can add it quickly

**Comment by l15n** [comment]
This is now working in production 😄

**Comment by colinthornton** [comment]
@l15n Awesome!
