### ISSUE TITLE
Update Outbreak Map colors

### ISSUE THREAD

**Issue by colinthornton** [reustle/covid19japan#183]
@reustle 

Just forwarding a suggestion I saw from user Jagariko on [Japan Times](https://www.japantimes.co.jp/liveblogs/news/coronavirus-outbreak-updates/) who are using the embed.

![image](https://user-images.githubusercontent.com/17635021/78317664-e590aa80-759d-11ea-9c4b-fff568da2c2f.png)

> The colour-coded map needs to be updated 201+ is very different from the 600+ that Tokyo actually has. It is misleading.

**Comment by ann-kilzer** [comment]
One suggestion would be to recalculate the data by percentile groups of 25%. (You might have already done that so pardon if I am repeating something)
