### ISSUE TITLE
Prototyping: Daily Confirmed by Prefecture

### ISSUE THREAD

**Issue by l15n** [reustle/covid19japan#198]
Starting to explore how to show the rate of change in cases by prefecture. 

First naive attempt:

<img width="694" alt="Screen Shot 2020-04-05 at 4 48 13 PM" src="https://user-images.githubusercontent.com/3714/78469567-65b13e80-775d-11ea-80e9-911812580ae5.png">

Values are low so it can get rather noisy.

Should probably be a moving average, probably 7-day.

**Comment by l15n** [comment]
Naive attempt at percentage change from previous day

<img width="689" alt="Screen Shot 2020-04-05 at 5 15 17 PM" src="https://user-images.githubusercontent.com/3714/78470031-15d47680-7761-11ea-8a1b-4ceeab08e123.png">

**Comment by reustle** [comment]
Thanks @l15n - this was added to the site for quite some time, and then expanded into the breakdown we have today. We appreciate it.
