### ISSUE TITLE
Pre-calculating data for prefecture trajectories

### ISSUE THREAD

**Issue by l15n** [reustle/covid19japan#199]
The Prefecture Trajectories chart uses the per-prefecture builds its data on-the-fly from the `dailyConfirmedCount` property of the prefecture data.

I think it would be a good idea  to move that calculation to the data repository, and also add data like a pre-calculated moving average where necessary. Only data directly needed for drawing charts would be added.

Currently:
- cumulative case count per prefecture

Possibly also:
- 7-day moving average of cumulative case count per prefecture
- 7-day moving average of daily case count  per prefecture

This is a tradeoff between extra calculation (and parsing of a larger JS file) on every client, versus a (slightly?) larger data payload.

**Comment by reustle** [comment]
I totally agree, the slight increase in payload size is negligible. Good idea 👌

**Comment by reustle** [comment]
I'm going to guess this is done. If not, we can reopen in the data repo. Thanks!
