### ISSUE TITLE
Visual guide

### ISSUE THREAD

**Issue by Kay-Cube** [reustle/covid19japan#2]
### Color
**Map**
#4C080A  #8E0000   #BA000D
#F44336  #FB9B7F   #FDEACB
#FFFFFF

**KPI**
#F44336   #BA000D
#1976D2   #004BA0
#37474F   #000A12

**Primary**
#FFFFFF  #EAEFF1  #A3ACBF  #000A12
#1976D2

### Typography & Font Size
Open Sans ExtraBold 48px
Open Sans Bold 34px
Open Sans Regular 21px
Open Sans Regular 16px
Open Sans Regular 12px

**Comment by reustle** [comment]
✅ 🙏
