### ISSUE TITLE
Move Prefecture Calculations Into Code

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#20]
We currently calculate metrics by prefecture within a sheet. This should be handled by the frontend on the raw patient data. The idea is to eventually move all calculations into Javascript, because dealing with multi-sheet spreadsheets as a data source is pretty fragile.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/304560/75095230-17ddde00-55d6-11ea-97e0-179304056f6c.png">

**Comment by liquidx** [comment]
This is mostly covered except there's still some of those columns our data is not good enough to cover (especially recovered and tested).

But confirmed cases is definitely now all calculated in code!

https://github.com/reustle/covid19japan-data/blob/master/src/summarize.js
