### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by olingern** [reustle/covid19japan#202]
@reustle 

Looks like the site is down:

![2020-04-07-134036_941x568_scrot](https://user-images.githubusercontent.com/1470297/78630707-6ec51b80-78d5-11ea-85a0-f30c78580b95.png)

**Comment by reustle** [comment]
I think that's a cache issue, works fine for me. Could you try a few hard refreshes? Try on your phone without connecting to the same wifi? (so DNS isnt shared).

Thanks for reporting!

**Comment by olingern** [comment]
Private window / non-cached version also seems down. Maybe your browser has it cached or maybe I'm hitting a CDN where it's not deployed?
![2020-04-07-134553_1021x531_scrot](https://user-images.githubusercontent.com/1470297/78631057-3a059400-78d6-11ea-8c6c-314cd2708396.png)

**Comment by olingern** [comment]
![32F12C23-E1AE-4C49-9ABA-5CCCC8C41003](https://user-images.githubusercontent.com/1470297/78631323-142cbf00-78d7-11ea-822a-5a5995d42b89.png)

Seeing same on iOS private window

**Comment by olingern** [comment]
Looks like it's up now :+1:

**Comment by reustle** [comment]
Thanks, reopening until I get more confirmations
