### ISSUE TITLE
Convert Flag Emojis To Unicode

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#208]
Reports are it doesn't work in Windows. It seems we may need to provide our own icons... I don't unicode will be enough. Thoughts?

https://github.com/lipis/flag-icon-css

**Comment by mertd** [comment]
![grafik](https://user-images.githubusercontent.com/7928036/78975228-9e328d00-7b4e-11ea-844e-0edae0256e8a.png)
This is what it looks like on Windows

**Comment by l15n** [comment]
Yeah, Windows 10 doesn't include the flag emoji.

Other options
* Skip the emoji on windows
* https://twemoji.twitter.com/ has the full set. Could probably set it up so that it is only loaded for Windows, and use their CDN hosted version?
