### ISSUE TITLE
Updated Header

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#215]
via @Kay-Cube 

New:
![image](https://user-images.githubusercontent.com/304560/78968776-602e6c80-7b40-11ea-8a4c-5124cd30e919.png)

Current:
![image](https://user-images.githubusercontent.com/304560/79034243-76dfcc80-7bef-11ea-9162-b2cbc7a02893.png)

**Comment by bmaniteja** [comment]
How can I Help ?

**Comment by reustle** [comment]
@bmaniteja Thanks for offering to help :) Are you able to make these changes on the UI?

**Comment by bmaniteja** [comment]
Please review https://github.com/reustle/covid19japan/pull/224
