### ISSUE TITLE
Collapse Prefectures Table

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#223]
We're now at a point where all prefectures are visible on the table, which is quite tall.

- [ ] Move the *Total* row to the top of the table
- [ ] Show only the top 10 prefectures by default
- [ ] Add a button at the bottom center of the table to show the hidden records

![image](https://user-images.githubusercontent.com/304560/79035211-35ebb600-7bf7-11ea-96ee-53e6227b590c.png)

Please note that the table now has more information than in this screenshot, which is fine.

Thank you!

**Comment by prajdabre** [comment]
I have managed to do this with one tiny tiny problem.

When I click on a button (more) to reveal additonal data, the trends (red bars) go haywire and then go normal if I simply change the tabs.

1. Before clicking on more
<img width="1280" alt="Screen Shot 2020-04-14 at 23 28 36" src="https://user-images.githubusercontent.com/8413449/79236378-d49e3e00-7ea7-11ea-909b-326bd4be3fef.png">

2. The messed up layout

<img width="1280" alt="Screen Shot 2020-04-14 at 23 28 42" src="https://user-images.githubusercontent.com/8413449/79236395-da941f00-7ea7-11ea-8464-32aedc64d3e4.png">

3. The layout fixes itself after a tab switch but the trends column becomes a bit wider for some reason
<img width="1280" alt="Screen Shot 2020-04-14 at 23 28 50" src="https://user-images.githubusercontent.com/8413449/79236527-057e7300-7ea8-11ea-8ae4-64fe6a3246f9.png">




Please check the screenshots.

Kindly let me know if you have a solution for this. I can make a PR for you to check if theres a fix for this.

**Comment by liquidx** [comment]
Thanks for trying to tackle this. I'm not sure why the redrawing seems to not work.

My recent PR changed the layout of the trend line to have a static width, so maybe that might help fix it. Can you see is that works?
