### ISSUE TITLE
Test performed on 'New cases' graph

### ISSUE THREAD

**Issue by maxgashkov** [reustle/covid19japan#230]
Feature request: it would be helpful to see 'number of tests performed' vs 'new cases by day' info. For example there is a drop of new cases on Apr 12. It's hardly an indicator of the declining rate of infection, more likely it's due to the fact that there were less tests performed on Sunday (?).

@reustle

**Comment by maxgashkov** [comment]
Obligatory 'thank you' for this website. Please stay safe and keep it up!

**Comment by reustle** [comment]
Thanks Max! It's definitely a good suggestion, and looks like it is also discussed here: https://github.com/reustle/covid19japan/issues/80

There is quite a lag in some of the data from the gov, and unfortunately the lags don't always match up (1 day delay, 2 day delay, etc).

I'll close this as a duplicate 🙏
