### ISSUE TITLE
Add 'Delta' dataset to help visualize rates of change

### ISSUE THREAD

**Issue by noodlefrenzy** [reustle/covid19japan#24]
https://github.com/reustle/covid19japan/pull/23

I wanted to see what the first and second derivatives looked like to help me decide when to stockpile food and start watching '28 Days Later' for survival tips.

**Comment by Kay-Cube** [comment]
We are working on adding the "delta". As for now, hopefully the "Outbreak Spread Trend" section would help 🤗

**Comment by noodlefrenzy** [comment]
Hi @Kay-Cube #23 is my PR to add that to the "Outbreak Spread Trend" graph. I'm trying to get a screenshot for you, need to install sass :). Feel free to ignore the PR, take whatever bits you want, or review/accept - whatever makes your job easier.

**Comment by reustle** [comment]
Do you suggest another term we can use instead of Delta that would be easier for non-native speakers? Appreciate you adding this!

**Comment by noodlefrenzy** [comment]
Hmm, nothing short unfortunately 😅. Best I could come up with was 'Daily Confirmed' or 'Change in Confirmed'.

**Comment by reustle** [comment]
How about `Daily Increase`? Also, maybe we can have a toggle to show/hide this value, as it might crowd the graph?

Attaching your screenshot from the PR
![image](https://user-images.githubusercontent.com/304560/75222537-ce64dd00-57e7-11ea-9ec8-06d9992867e2.png)

**Comment by noodlefrenzy** [comment]
I can do that (re: Daily Increase). I'll take a look at the code and see if I can grok how to add a toggle for that series.

**Comment by reustle** [comment]
Also, sorry about all the recent changes (merge conflicts likely).

**Comment by noodlefrenzy** [comment]
It seems like clicking on the legend auto shows/hides the dataset if you use the built-in legend from Chartjs - is there a reason you turned that off and built your own?
