### ISSUE TITLE
Update Entry Ban List

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#263]
https://www.japantimes.co.jp/news/2020/04/27/national/japan-extend-entry-ban-russia-13-countries-abe-says/

Russia, Saudi Arabia, United Arab Emirates, Antigua and Barbuda, Barbados, Belarus, Djibouti, the Dominican Republic, Kuwait, Oman, Peru, Qatar, Saint Kitts and Nevis, and Ukraine

**Comment by colinthornton** [comment]
Working on this now.
