### ISSUE TITLE
Redesigning application

### ISSUE THREAD

**Issue by dlinx** [reustle/covid19japan#264]
@reustle 
The current layout is vertical, much lengthy, and needs to scroll more to check the data. There is much empty space on both sides of the data. Restructuring the data may improve the user experience.

**Comment by liquidx** [comment]
Do you have a proposed design on what it should look like?

**Comment by dlinx** [comment]
@liquidx How about this one?
![image](https://user-images.githubusercontent.com/5583697/80597482-ddc00b00-8a62-11ea-91ab-a8a358f08579.png)

**Comment by liquidx** [comment]
Thanks for taking a go at this. @Kay-Cube is working on a revised version of the site that is more compact, but still responsive across different screen sizes. We'll take some of this into consideration.

**Comment by reustle** [comment]
Thank you very much @dlinx - This was helpful feedback as we continued to redesign the site. We appreciate your contributions.
