### ISSUE TITLE
「既存感染者数」について・About "Number of existing infections"

### ISSUE THREAD

**Issue by TechnicalSuwako** [reustle/covid19japan#265]
// Please tag @reustle in your newly created issue

https://github.com/reustle/covid19japan/pull/193

３週前、「既存感染者数」というテーブル列を追加しましたが、
最近消えました。
間違えましたか？又は…

Three weeks ago, I added a table column called "Number of existing infections",
It has recently disappeared.
Did you make a mistake? Or ...

I am sorry that I was translated into English by an automatic translator.

**Comment by liquidx** [comment]
Thanks for your question. I removed it in my latest pull request because there was too much information on that table.

The 既存感染者数 count was very similar to 感染者数, so it didn't provide more value than that number.
