### ISSUE TITLE
[Lighthouse] Optimize Mapbox Network Usage

### ISSUE THREAD

**Issue by liquidx** [reustle/covid19japan#269]
Mapbox is downloading a lot of font files according to Lighthouse. 

We should see if in the short term we can tune it or consider again making the map static.

<img width="813" alt="Screen Shot 2020-04-29 at 0 38 51" src="https://user-images.githubusercontent.com/72062/80507461-d68cf480-89b1-11ea-82a8-366e7c5a40d6.png">

**Comment by ChrisLoer** [comment]
I can't actually see the font ranges in the screenshot, but that's almost certainly Japanese character ranges being downloaded. You can avoid that by having Mapbox ask the browser to render the characters locally: https://docs.mapbox.com/mapbox-gl-js/example/local-ideographs/.

**Comment by liquidx** [comment]
Thanks for the hint with the fonts. Going to see if that helps reduce the amount it's pulling down.

**Comment by reustle** [comment]
Thanks again! Moving to static maps really helped here.
