### ISSUE TITLE
Add City-Level Data

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#27]
Do we have the ability to move from prefecture-level to city-level? It seems like many published cases include this information.

How would they be visualized?

**Comment by amwfarid** [comment]
Assuming the data can be made available on the spreadsheet, I can propose the following implementations:

**Map perspective:**
We can visualize city level statistics by plotting lat/lng markers (of cities) on the map once a close-enough zoom level is reached (say at the present max zoom=7).

The current geojson only contains the bounds for the prefectures, it'd be time consuming to track down geojson files per each prefecture and integrating them. I haven't yet found one geojson file that has city level separation on the entire level of Japan.


**Graph perspective:**
We could add two drop menus (prefecture -> city) in the "spread trend" area and reload the graph accordingly.

**Comment by exhaze** [comment]
This is the raw data published by MLIT: http://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-N03-v2_3.html

It has GeoJSON data for every single city and prefecture.

**Comment by reustle** [comment]
Thinking we should use Clustering to show this data.

https://docs.mapbox.com/mapbox-gl-js/example/cluster/

https://blog.mapbox.com/clustering-properties-with-mapbox-and-html-markers-bb353c8662ba

Question I still would like to hear suggestions about, how do we handle cases with no city defined? Do we default them to the center of the prefecture? The biggest city of the prefecture?

![image](https://user-images.githubusercontent.com/304560/75733512-e03f0680-5d38-11ea-827f-19b076bc6bb4.png)

![image](https://miro.medium.com/max/862/0*g09phU_4zwOEcd-8.gif)

**Comment by liquidx** [comment]
That's very cool. 

My suggestion is for the cases we don't have the data, center of the prefecture is probably good enough since it could be any of the towns, not necessarily the biggest one.

**Comment by l15n** [comment]
> My suggestion is for the cases we don't have the data, center of the prefecture is probably good enough since it could be any of the towns, not necessarily the biggest one.

That's what https://coromap.info/ does, so having a look at the cases can give you a good idea of what it looks like. e.g. Case 117's visit to Hiroshima Prefecture, Case 328 in Okayama etc.

**Comment by olingern** [comment]
I'm interested in this as I'm a semi immune compromised person who is trying to find the best place to wait the pandemic out.

I've collected the cities data into a map and normalized the map keys, but some of the data isn't perfect. So far, I've normalized the casing ( i.e. some cities are coming back in multiple casings ) and converted comma separated values to something key-able, ex. "Kumamoto, City" -> "KUMAMOTO_CITY"

**Question 1: city keys**
There's a few more cases to handle, but the browser _might_ not be the best / most performant place to do this. Maybe the data source is a better place to do such work. Thoughts?

**Question 2: displaying aggregated data**
Maybe displaying multiple white dots that can be click on to see the city info? There will probably be overlap and users will need to zoom in to click on the exact city they want.


Here's a sample log:

```
KUMAMOTO_CITY: 9
KURUME: 2
KUSATSU: 5
KUSHIRO: 8
KUTCHAN: 1
KUWANA: 1
KYOTANABE_: 1
KYOTO: 8
KYOTOGUN: 1
KYOTO_CITY: 71
MAEBASHI: 1
MARUKAME: 1
MATSUDO: 13
MATSUHARA: 2
MATSUMAE: 2
MATSUMOTO: 3
MATSUYAMA: 2
MATUSMOTO: 1
MIKAWA: 1
MINAMI_WARD_NIIGATA: 1
MINOO: 3
MISATO: 1
MIYAKICHO: 1
MIYAZAKI: 1
MIYAZAKI_CITY: 3
MIYOSHI: 1
"MIYOSHI-CHO": 1
```

**Comment by liquidx** [comment]
The city-level data is a little inconsistent and not always reported, nor are we completely consistent in inputting this data since there are two fields this can be in (residence or confirmed). You can be confirmed in one city, but live in another (sometimes even in another prefecture).

The granularity is also inconsistent, sometimes it's an area (like Aichi will report someone positive from an area that includes multiple cities/towns). But sometimes they're very specific.

confirmedByCity are just ones where we've included the city. Not all the data has that information in it. One approach would be to post-process that information and merge it (e.g. Miyazaki vs Miyazaki city) - at least try to merge the known cities in the data.

Right now, that post-processing can be done in the covid19japan-data repo.

https://github.com/reustle/covid19japan-data

**Comment by olingern** [comment]
@liquidx I see. It sounds like this wouldn't be useful as it could be misleading or inaccurate.

**Comment by reustle** [comment]
Closing this for now :)
