### ISSUE TITLE
Cleanup Travel Restrictions

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#277]
We can hide or remove these currently unused sections

![image](https://user-images.githubusercontent.com/304560/80586947-b7916f80-8a50-11ea-9a9e-7688e465d901.png)

**Comment by ekerik220** [comment]
https://github.com/reustle/covid19japan/pull/278

This will just hide the sections when they are empty. Just in these sections are used again in the future.

**Comment by mertd** [comment]
Are there any other changes necessary other than #278 ?

**Comment by liquidx** [comment]
Removed those unused sections now.
