### ISSUE TITLE
Mapbox optimization: host data on Mapbox servers

### ISSUE THREAD

**Issue by ChrisLoer** [reustle/covid19japan#280]
I haven't done any profiling of your map performance and I don't know what the pain points are (memory, CPU time, time to first render, etc.), but just at a quick glance one slow step is probably downloading the prefecture GeoJSON and then tiling it locally. Instead, you could upload the data to be hosted by mapbox, and instead of adding the extra source/layers on the client side, you could make a style in Mapbox studio that had the prefecture data composited in. This way, the cost of loading your annotated map would be similar to just loading the base map.

If you wanted to go a step further, you could modify `covid19japan-data` to upload case counts etc. directly to a Mapbox hosted GeoJSON tileset (it's not too tricky with the uploads API: https://docs.mapbox.com/help/tutorials/upload-curl/#stage-your-file-on-amazon-s3). Then the only non-Mapbox client side code you'd have running would be the little bit to add the detail popup.

If you want to go down the "static map" approach (issue #39), uploading the data to Mapbox servers would enable you to use the Mapbox static maps API instead of having to roll your own code to generate the map locally and store the image on your server. Personally I wouldn't start with trying to make it static, because (1) even if it's not too interactive right now, being interactive gives you a lot more flexibility to do things like drill-down to ward-level data, and (2) drawing client side really shouldn't be that expensive (the biggest deal is just the first un-cached load: downloading a few hundred KB of the mapbox-gl package, and a few hundred KB more worth of vector tiles depending on what you're showing).

cc @reustle @liquidx

**Comment by reustle** [comment]
Hey Chris, sorry that we didn't reply to this earlier. We've gone ahead and used static maps as per your suggestion, and it has been a huge improvement. We really appreciate the help. Swing by our GeoTokyo.com event if you're ever around. Thank you.
