### ISSUE TITLE
Making it easier to add new languages

### ISSUE THREAD

**Issue by mertd** [reustle/covid19japan#289]
When making changes to #218 in #288 to add Spanish as a new language, I noticed that it is not enough to follow the steps for adding new languages as I documented in the Readme, at least for full support of the "Last updated" info. Instead, some changes that go slightly beyond adding a new value to an array have to be made in `src/components/Header/DrawLastUpdated.js`.

Additionally, the new language needs to be added to `src/index.html` if the list should look as similar as possible before and after the automatic language selector generation kicks in.

I suggest we either document the additional changes necessary, or try to lower the hurdle for less technical people who want to help with translations and remove the need to edit two more files.

@reustle

**Comment by colinthornton** [comment]
It looks like the prefecture trajectory chart also has EN/JP hardcoded in right now:

![image](https://user-images.githubusercontent.com/17635021/81023610-e756d200-8eab-11ea-90a8-c7c90ce827c4.png)

**Comment by liquidx** [comment]
We should swap the order around so that it defaults to English/Romaji version of the names for non-JA.

**Comment by colinthornton** [comment]
I'll look into if it's possible to query i18next for the list of initialized languages in order to automate the generation of those elements, that way adding a translation would only involve adding a .json file and editing the base markup.

**Comment by mertd** [comment]
> I'll look into if it's possible to query i18next for the list of initialized languages in order to automate the generation of those elements, that way adding a translation would only involve adding a .json file and editing the base markup.

You can read the exported LANGUAGES array in `src/i18n/index.js` for all languages. I introduced it  with the thought of having just one location that needs editing in the source files to add a new language in the long term. i18next also used that array to know which json files to look for.
