### ISSUE TITLE
Update properly, especially Tokyo

### ISSUE THREAD

**Issue by kenmawer** [reustle/covid19japan#292]
// Please tag @reustle in your newly created issue

Sorry if I may not be doing this properly, but I am new to Github.

I have working proficiency in Japanese, so even though my speaking is rather broken, I can understand the news articles without much translation.

First, I should mention that we should keep with the standards of this site:
https://www3.nhk.or.jp/news/special/coronavirus/latest-news/

Also, as someone from Tokyo, I noticed that its recovery count is stuck at 59. There are more people being discharged from hospitals. However, their recoveries have yet to be verified.

I just want to help out with personal projects relating to getting co-op jobs, but unfortunately, I don't have that experience in the first place (but am willing to acquire).

Thank you for your understanding.

**Comment by liquidx** [comment]
Thanks for the feedback!

Do you have a source for where the recovery number is that is different from what we have? We are getting the number from MHLW:
https://www.mhlw.go.jp/stf/newpage_11146.html

**Comment by kenmawer** [comment]
Oh yeah, it looks better now. That is what I was referring to (or maybe something in Japanese that was also using those numbers).

Speaking of which, one feature I would suggest is comparing Tokyo and Kanto to the rest of Japan.

**Comment by liquidx** [comment]
Yes, we switched to using the Tokyo Government reported number rather than the MHLW one. The MHLW one hadn't been updated for a while for Tokyo (at 59 for the last two weeks), so it's increasingly inaccurate. 

We recalculated all the our recovery numbers to use the Tokyo number now.
