### ISSUE TITLE
Sheet Data Cache

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#31]
Google sheets is starting to throw some 500 errors now that we're well past 100 concurrent users at any time. Let's create a script to pull the sheet values every 5 minutes and save a json file somewhere. Github Gist? S3?

**Comment by olingern** [comment]
How is this deployed? Is there access  (or could there be) to cron or a serverless environment?

Writing a JSON file to S3 could work

**Comment by reustle** [comment]
Not yet but I might deploy a script to one of my servers, here's what @franciscop and I came up with so far. Essentially this can run every 5 minutes, and dumps the json into a file that NGINX serves. If the script fails, the JSON will simply get slightly outdated which is better than the site going down.

``` javascript
//const http = require("http");
const drive = require("drive-db")

const SHEET = "SHEET_ID"
const SHEET_PREFECTURES_TAB = 2
const SHEET_DAILY_SUM_TAB = 3
const SHEET_LAST_UPDATED_TAB = 4
const CACHE = 5 * 60 // 5 min

const tabs = {
  prefectures: SHEET_PREFECTURES_TAB,
  daily: SHEET_DAILY_SUM_TAB,
  updated: SHEET_LAST_UPDATED_TAB
}

const readAndSave = async tab => {
  const data = await drive({ sheet: SHEET, tab: tabs[tab], cache: CACHE })
  // write `JSON.stringify(data)` to `${tab}.json`
}

Promise.all(Object.keys(tabs).map(readAndSave))
```

**Comment by olingern** [comment]
I can pick up on #31 if you'd like. It might be fun to play with Github Actions for this. S3 may be overkill and using Github gist as a JSON host is a pretty interesting idea.

**Comment by reustle** [comment]
@olingern Thanks! @python273 and I are nearly done with this actually, went ahead with s3 for now. If you want to play around with the actions+gist idea, go for it though. I think everything can be defined entirely in code in the repo, right? PR welcome :)
