### ISSUE TITLE
昨日今日の比較は可笑しい

### ISSUE THREAD

**Issue by TechnicalSuwako** [reustle/covid19japan#327]
// Please tag @reustle in your newly created issue

お世話になっております。

昨日と今日の数を確認ところ、
昨日、感染者数は15628人、回復者数は8216人、死亡者数は630人そうして既存感染者数は6782人でしたと、
今日は感染者数は15695人、回復者数は8478人、死亡者数は634人そうして既存感染者数は6583人です。

でも、既存感染者数だけは可笑しいと思います。
6782 - 6583 = 199
現在、-199じゃなくて、-530と表示しています。

この問題は一番上のやつだけにあります。
「ウイルス感染の拡散傾向」でホバーしたら、正しい数が出てきます。

**Comment by liquidx** [comment]
(Sorry, my Japanese is not good, ごめん〜)

I think you are right, I'm not sure with it says -530 in the chart in the number at the top, but -199 in the Total Cases chart.

![Screen Shot 2020-05-11 at 14 04 44](https://user-images.githubusercontent.com/72062/81525686-75412a00-9390-11ea-9571-7a5c3587e4d3.png)

![Screen Shot 2020-05-11 at 14 04 39](https://user-images.githubusercontent.com/72062/81525698-7c683800-9390-11ea-8842-e32d07d7b474.png)

The calculation that's done in the graph is right, so I think we might have a mistake in the way we calculate the day-to-day differences. 

Thank you for pointing that out.

**Comment by TechnicalSuwako** [comment]
了解！
