### ISSUE TITLE
User front-end  framework to facilitate development of aforementioned feature requests

### ISSUE THREAD

**Issue by YoitsuKamijo** [reustle/covid19japan#34]
@reustle 
I would love to contribute, I am familiar with Vue.js framework, but can also pickup React.js if everyone else is more comfortable.

**Comment by reustle** [comment]
Hello @YoitsuKamijo ! Thanks for offering to help.

I would like to fully understand why you feel the project should be switched from vanilla JS to a framework like Vue or React. Do you think it would make it much easier to implement new features? Do you think the current code is not performing adequately? Or do you just feel most comfortable using a framework?

At [our company](https://reustle.co) we use React almost exclusively, but are often building much larger projects with multiple developers. There is definitely value to be had with a framework, but it does come at a cost of a more complicated development environment. With the current system in place and no build system required, it's much easier for someone to pull the code down and run it locally, while making small changes.

Thank you again!

**Comment by reustle** [comment]
Closing as no reply, can re-open later
