### ISSUE TITLE
Spanish translation file error

### ISSUE THREAD

**Issue by Luistecnologico** [reustle/covid19japan#359]
The file that containing the resources in Spanish is missing the line corresponding to "top-prefectures".
the following line should be added `"top-prefectures": "Top 10 Prefecturas",`
@reustle

**Comment by vlumi** [comment]
There are other missing Spanish translations in #351 :
* In language selector: "Languages"
* Column titles in Top 10 Prefectures: "Today", "Yesterday"
* Legend in Nuevos casos diarios: "Daily", "7-day average"

I can create a pull request for these if you (or someone else) can translate them.

**Comment by reustle** [comment]
I was notified of these changes as well by LMendo

> Please change “Activo” into “Activos” it’s weird all the other headers are in plural except that one

> Also, “Prefecturas” should not be capitalized unless at the beginning of a sentence. Therefore “Top 10 Prefecturas” should be “Top 10 prefecturas” and “Trayectorias de casos confirmados por Prefectura” should be “Trayectorias de casos confirmados por prefectura”

**Comment by liquidx** [comment]
The fixes are now applied, thanks!
