### ISSUE TITLE
【京都府】既存感染者数：-18？？

### ISSUE THREAD

**Issue by TechnicalSuwako** [reustle/covid19japan#362]
// Please tag @reustle in your newly created issue

京都府の数字はちょっと可笑しいと思いますね（；^ω^）
![image](https://user-images.githubusercontent.com/15627184/83932386-0e6f2f00-a7dd-11ea-971b-7702a39f4220.png)

**Comment by liquidx** [comment]
Thanks for letting us know the mistake. We've fixed the data issue with mixing up the recovered number and the confirmed number.

**Comment by TechnicalSuwako** [comment]
修正された課題へご返信致しまして失礼します。
今回は広島県で同じ問題があります。

宜しくお願い致します。

![image](https://user-images.githubusercontent.com/15627184/84380497-62857380-ac22-11ea-9b7c-e248140a7cd1.png)

**Comment by TechnicalSuwako** [comment]
@liquidx

**Comment by liquidx** [comment]
This is now fixed. Hiroshima counts reinfected patients twice, and their recovery twice, so our numbers don't match. 

https://docs.google.com/spreadsheets/d/1vkw_Lku7F_F3F_iNmFFrDq9j7-tQ6EmZPOLpLt-s3TY/edit#gid=1399411442

![Screen Shot 2020-06-13 at 0 21 39](https://user-images.githubusercontent.com/72062/84518597-e36c6a00-ad0b-11ea-8b09-eccea32af78e.png)
