### ISSUE TITLE
Prefectures with no cases (Iwate) behave differently

### ISSUE THREAD

**Issue by vlumi** [reustle/covid19japan#363]
Hi @reustle 

All but Iwate have cases by now, so that one prefecture not showing up on the prefecture list or having a popup on the map feels a bit weird -- I think it would be clearer to just show it as zero cases.

**Comment by liquidx** [comment]
I just updated the data side to return Iwate data even if it's all 0s.

https://github.com/reustle/covid19japan-data/commit/de3ab1f8936831e86b094c9b7797d9e6455e2775
