### ISSUE TITLE
Allow changing time period of main charts

### ISSUE THREAD

**Issue by vlumi** [reustle/covid19japan#365]
Hi @reustle 

With the second wave coming, it would be nice to see the full time scale and compare with the first wave -- especially for "Total Cases" and "Daily Confirmed Cases". However, the charts are currently truncated to the last 60 days only, so only the tale of the first wave is visible.

Only showing the recent trend is probably a good default behavior (to see current status at a glance), but having the option to show since the beginning (or another longer/shorter period) would be a nice option to have.

**Comment by liquidx** [comment]
I added a quick selector at the start of the chart section to draw the graph over 6 months and 3 months so you can see the trends. #454
