### ISSUE TITLE
More Travel Bans

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#373]
https://www.japantimes.co.jp/news/2020/06/29/national/japan-adds-17-nations-to-coronavirus-entry-ban/#.XwEf8feRW8F

Guyana, Cuba, Guatemala, Grenada, Costa Rica, Jamaica, Nicaragua, Haiti, Saint Vincent and the Grenadines, Algeria, Eswatini, Cameroon, Senegal, Central African Republic, Mauritania, Iraq, Lebanon and Georgia.

**Comment by liquidx** [comment]
Seems to be fixed in #374
