### ISSUE TITLE
Static Map Image

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#39]
Instead of loading mapbox on every page load, let's generate an image of the map and prefectures once every 5 minutes (like we do with the json cache) and store it on s3.

Once the user clicks the image, it will then load the real mapbox which they can interact with. I would bet that >75% of users don't touch the map, so loading mapbox isn't necessary.

**Comment by python273** [comment]
I think we could take geojson and convert to svg to replace mapbox completely

https://github.com/deldersveld/topojson/blob/master/countries/japan/jp-prefectures.json
https://exploratory.io/map

**Comment by reustle** [comment]
This is a great idea, I'm wondering how it will change the way we do #27. Since we seem to have geojson data there too, it may not be a problem?

**Comment by python273** [comment]
https://exploratory.io/map has cities dataset, but no English names and each city is not a single ploygone
<img width="1015" alt="Screenshot 2020-02-27 at 17 04 14" src="https://user-images.githubusercontent.com/3097956/75452509-7f53af00-5983-11ea-8ea6-1ed4ea004159.png">

**Comment by python273** [comment]
this one seems slightly better
https://github.com/deldersveld/topojson/blob/master/countries/japan/jp-towns.json

**Comment by reustle** [comment]
FTR

https://docs.mapbox.com/help/how-mapbox-works/static-maps/

https://api.mapbox.com/styles/v1/mapbox/light-v10/static/139.083,38.0965,4.03/650x400?access_token=pk.eyJ1IjoicmV1c3RsZSIsImEiOiJESzd6YVRnIn0.Hh9AwQw1X0PR_TOewZMMzA

**Comment by olingern** [comment]
From #47 

> Due to the quickly rising cost of hosting Mapbox on the site

I'm wondering if instead of switching to svg from mapbox, someone reaches out to mapbox and see if they would give the project a pass since it's benefiting many people in Japan

**Comment by reustle** [comment]
https://twitter.com/reustle/status/1234371319321387008 🤞

**Comment by reustle** [comment]
They've offered to help out which is great, but I still think something like their 'static map' on load would be nice for the user. Once you click the map, it loads the interactive version in its place.
