### ISSUE TITLE
Bundle JS Libraries

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#40]
We are importing a lot of libraries at this point. Let's pull them all into a single file and save them within the repo, and load them as one file. Probably good to use `webpack`.

**Comment by tatellos** [comment]
Will do this in conjunction with #41 .

**Comment by olingern** [comment]
Just wanted to comment and say that bundling, IE support, pwa, front-end framework, etc. is handled out of the box in [Gatsby](https://www.gatsbyjs.org/) (another static site generator). Not that the project should switch, but re-inventing an existing tool chain is something to be aware of.

**Comment by reustle** [comment]
Good to know, thanks @olingern - One of the reasons I pick Jekyll is because github pages supports it out of the box. Looks like [using gatsby with github pages](https://www.gatsbyjs.org/docs/how-gatsby-works-with-github-pages/#deploying-to-a-path-on-github-pages) still requires running some build commands. Not the end of the world, but worth noting.
