### ISSUE TITLE
Today various statistics are displaying incorrectly, map empty

### ISSUE THREAD

**Issue by OsakaStarbux** [reustle/covid19japan#411]
@reustle 
The app seems broken today. Some zero stats and graph labels are wrong. 
![IMG_8601](https://user-images.githubusercontent.com/7752014/88387480-790c1680-cded-11ea-9ed0-3c52be845916.PNG)
![IMG_8602](https://user-images.githubusercontent.com/7752014/88387483-7c070700-cded-11ea-9576-ebaa07202c3c.PNG)
![IMG_8603](https://user-images.githubusercontent.com/7752014/88387484-7c9f9d80-cded-11ea-8786-656477b8c7fe.PNG)
![IMG_8604](https://user-images.githubusercontent.com/7752014/88387486-7d383400-cded-11ea-8b13-5acefc7e8023.PNG)

**Comment by liquidx** [comment]
Is it still a problem? It is working for me at the moment.

**Comment by liquidx** [comment]
Oh, I think I know what happened. We had some issues earlier with the data in the spreadsheet and some numbers were set to 0. We'll try to prevent that from polluting the data in the future.
