### ISSUE TITLE
Adding credit for Gilles Gouaillardet

### ISSUE THREAD

**Issue by liquidx** [reustle/covid19japan#415]
@ggouaillardet - you've been contributing a ton to the data and also several PRs. I'd like to credit you on the site, would you be happy to be listed on the site? 

If so, let me know what link/avatar image (50x50) you'd like.

**Comment by ggouaillardet** [comment]
Thanks! You can use my github avatar https://avatars1.githubusercontent.com/u/7233259?s=80&v=4
