### ISSUE TITLE
Backend Data Validity Check

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#42]
Like https://github.com/reustle/covid19japan/issues/11 but on the new backend cache code

Simple example https://github.com/reustle/covid19japan/commit/6bd933ba17e71f3c9b9a8017add923d6b5612a6c#diff-45a12245c90c3f724f1644a02264341eR29

**Comment by reustle** [comment]
@liquidx sounds like your latest work covers this partially or completely 🙏

**Comment by liquidx** [comment]
I think this is mostly fixed now. It'll be done in the data generation side. Here's an example:

https://github.com/reustle/covid19japan-data/blob/master/src/verify.js
