### ISSUE TITLE
Replace Google Analytics with Plausible

### ISSUE THREAD

**Issue by n-himitsu** [reustle/covid19japan#438]
@reustle It would be great if the website used privacy-friendly analytics instead. 

Here are some suggestions, all of which are open-source and possible to self-host: 
- [Plausible](https://plausible.io): Half-price for open-source projects
- [Goatcounter](https://goatcounter.com): Free for non-commercial projects upto 100K views/month
- [Matomo](https://matomo.org)

**Comment by reustle** [comment]
Hey, thanks for the suggestions! For the time being, we will likely keep it as Google Analytics for the sake of simplicity and integration with our existing systems / workflows, but I understand the desire to move more towards a different provider.

I'll let you know if we get closer to a point where that might change. Thanks again for the submission.

**Comment by reustle** [comment]
@n-himitsu Thanks again for submitting this. I think it is a good time to install Plausible and get rid of Google Analytics.

Let's remove Google Analytics and instead use Plausible.io

```
<script async defer data-domain="covid19japan.com" src="https://plausible.io/js/plausible.js"></script>
```
