### ISSUE TITLE
Missing linked content 

### ISSUE THREAD

**Issue by tassoman** [reustle/covid19japan#442]
@reustle Each country flags links to http://www.moj.go.jp/content/001316999.pdf but the file is not found.

**Comment by pageman** [comment]
@reustle found the updated file at http://www.moj.go.jp/content/001329914.pdf here's a pull request https://github.com/pageman/covid19japan/pull/1

**Comment by reustle** [comment]
Thank you both!

**Comment by pageman** [comment]
@reustle here you go https://github.com/reustle/covid19japan/pull/443

**Comment by reustle** [comment]
Resolved, thanks everyone
