### ISSUE TITLE
Redesign the "Total cases" graph (?)

### ISSUE THREAD

**Issue by ggouaillardet** [reustle/covid19japan#447]
@reustle Currently, the "Total cases" graph (the first one on the left from the web interface) plots
 - Confirmed: ~100k
 - Recovered: ~100k
 - Active: ~10k
 - Deaths: ~1k

These are three order of magnitudes plotted on the same linear graph
 - Confirmed cases is easily readable
 - Recovered cases is also easily readable, and basically "follows" the Confirmed cases line
 - Active is harder to read
 - Deaths is basically flat and impossible to read.

There are imho different options to improve the readability:
 1. plot on a logarithmic scale
 2. Stop plotting Confirmed and Recovered lines
 3. plot the new confirmed cases (~1k, similar range than Deaths)

**Comment by liquidx** [comment]
I agree that the total cases chart is getting a little useless now. 

I think we should plot just the active cases and then a separate one for deaths?

**Comment by reustle** [comment]
Thanks for submitting this, and I agree with @liquidx . I think a separate graph would be a good move. I appreciate it!

**Comment by liquidx** [comment]
Merged #454 that splits these charts up now. I've also added a way to look at the last 3 months vs 6 months (right now labelled all-time).
