### ISSUE TITLE
Chiba has negative active cases?

### ISSUE THREAD

**Issue by ronkorving** [reustle/covid19japan#448]
// Please tag @reustle in your newly created issue

The map shows this really well. There are more Recovered than Confirmed. Which also ends up being displayed as "0 active cases", which I highly doubt. I wonder what could cause this.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/631240/98783352-c4017680-243c-11eb-8dbf-11ed81c6c5a0.png">

**Comment by liquidx** [comment]
We made a typo in the data, it should be fixed in the next data update. Thanks for reporting.

**Comment by ronkorving** [comment]
Thanks! You're all doing amazing work!
