### ISSUE TITLE
Link to countries' restrictions PDF is broken

### ISSUE THREAD

**Issue by NicoleRauch** [reustle/covid19japan#449]
@reustle The link http://www.moj.go.jp/content/001329914.pdf does not work any more...

BTW it seems that all countries link to the same PDF file; isn't it a bit wasteful to add so many links (and make the user search for the desired country in this dense list, and making them - or at least me - believe that they will immediately get information specifically tailored to the country)? In other words, wouldn't a single link suffice?

**Comment by liquidx** [comment]
I agree here that it's not that useful to link all the countries any more.

Maybe better to point visitors to either the rules for Foreign Resident Re-Entry:
http://www.moj.go.jp/nyuukokukanri/kouhou/nyuukokukanri07_00245.html

There is also a link on that site to the probably updated PDF (in Japanese) that describes the full list:
http://www.moj.go.jp/content/001327502.pdf

**Comment by reustle** [comment]
I also agree, thanks for posting this. Maybe we could remove this section entirely and just add a link to the page(s) that @liquidx provided?

**Comment by NicoleRauch** [comment]
The link to the PDF seems to be quite fragile (looking at the past issues, it already changed at least once before) and it's prominently linked in the website behind the first page, so my vote would be for just adding that page and letting the users access the PDF from there.

**Comment by liquidx** [comment]
Removed the PDFs and now linked to a variety of government and news sites that describe the latest rules.
