### ISSUE TITLE
Move Okinawa from Kyushu to its own region

### ISSUE THREAD

**Issue by aatrani** [reustle/covid19japan#450]
@reustle  

At the moment, Okinawa's data is combined together with the Kyushu region.
  
This does not make much sense, because Okinawa is very geographically distant from Kyushu. 

More importantly, it prevents Okinawa from being compared to the other regions in the regions' graph, and pollutes the data of the Kyushu region.

Unless there's some specific reason to keep Okinawa within Kyushu, I suggest to move Okinawa to an individual region. 
 Hokkaido, for example, is part of its own region, despite being much closer to Tohoku than Okinawa is to Kyushu

**Comment by ann-kilzer** [comment]
According to [Wikipedia on regions of Japan](https://en.wikipedia.org/wiki/List_of_regions_of_Japan):
"Kyūshū is generally combined with Okinawa Prefecture as Kyūshū Region."

**Comment by aatrani** [comment]
@ann-kilzer I see, I didn't know about this. Quite strange given how distant Okinawa is from mainland, both geographically and culturally

For practical purposes, I still think it is a bit confusing putting together Okinawa and Kyushu in the statistics, also given how different is the pandemic trend between the two islands.

**Comment by reustle** [comment]
Thank you for submitting this. For the time being, we will keep them grouped for simplicity.
