### ISSUE TITLE
Graph for number of tests over time 

### ISSUE THREAD

**Issue by osdiab** [reustle/covid19japan#451]
// Please tag @reustle in your newly created issue
@reustle 

From the perspective of “is the government testing people” would be nice to see a similar tests over time graph like the cases one

![D4D254AD-E8E1-465F-982A-69D879C43E3E](https://user-images.githubusercontent.com/1890926/99796271-8903ef00-2b70-11eb-8448-935e14aff62a.jpeg)

**Comment by liquidx** [comment]
Added an expanded graph that shows the number of tests over time. 

https://covid19japan.com/#tested
