### ISSUE TITLE
Add Nepali Language

### ISSUE THREAD

**Issue by Ashok314** [reustle/covid19japan#472]
Hello @reustle,
I have created the translation for the Nepali language. 
There is mention about the language in [#347 ](https://github.com/reustle/covid19japan/pull/347#issue-421828086) previously. 
Though the writing script is the same these are completely different languages. 

If you consider adding the Nepali language I will create a PR.
Here are some screenshots. 

![Covid_japan_np_lang_1](https://user-images.githubusercontent.com/43514261/102687668-0d12ca80-4234-11eb-8ff2-a6688ce0fccb.png)
![covid_japan_np_lang_2](https://user-images.githubusercontent.com/43514261/102687670-0dab6100-4234-11eb-9f82-e0b5c875854e.png)

Reference: [Nepal Government Dashboard](https://covid19.gov.np/),  [Covid-19 Nepal, Open Source](https://covidnepal.org/)

**Comment by reustle** [comment]
Hey @Ashok314 thank you so much for the submission, and sorry for not getting back to you sooner. Your PR was merged back then, so I'll close this.
