### ISSUE TITLE
Add another label for colorisation to the outbreak map

### ISSUE THREAD

**Issue by a-ogilvie** [reustle/covid19japan#475]
@reustle 

Currently there is no differentiation between e.g. Tokyo (20k active cases) and Tochigi (1.5k active cases) on the outbreak map.

I suggest we add another level to the map:
* No cases
* 1-49 cases
* 50-99 cases
* 100-499 cases
* 500-999 cases
* 1,000-9,999 cases
* **10,000+ cases**

If we want to maintain the symmetry of having 6 labels, we could join case 2 and 3 together into e.g. 1-99 cases.

**Comment by reustle** [comment]
I agree that the colors don't make a whole lot of sense, as they are basically a population heat map. I think we should have a larger discussion about what to show instead of the outbreak distribution. Testing and vaccine centers nearby? Will create an issue for this shortly. Thanks!
