### ISSUE TITLE
Add Vietnamese

### ISSUE THREAD

**Issue by hoangsonbk** [reustle/covid19japan#478]
Hi @reustle @liquidx  @l15n 

First of all, thank you very much for this amazing project, it's super useful during this time.

I would like to contribute to the project by adding Vietnamese as we have a relatively big Vietnamese community in Japan and this will be a very helpful source of information regarding the covid-19 situation in Japan. I have a PR already so it would be great if you guys can add me as a contributor so I can send it out for review.

Best regards.

**Comment by liquidx** [comment]
Thanks for offering, feel free to send us a pull request and we can review it.

**Comment by reustle** [comment]
Hi @hoangsonbk - thanks for the suggestion. If we see a pull request, we'd be happy to review it. You don't need to be a contributor to submit PRs to open source projects. Thank you.
