### ISSUE TITLE
Advance Critically Ill visualization

### ISSUE THREAD

**Issue by czymra** [reustle/covid19japan#480]
The Toyokeizai visualizations are going to be discontinued, or at least stop being updated from February 1st https://toyokeizai.net/sp/visual/tko/covid19/en.html 

One of the most insightful visualizations there is "Critically Ill" and I think it would be fantastic if it could be included here.

<img width="465" alt="Screen Shot 2021-01-24 at 20 15 25" src="https://user-images.githubusercontent.com/12640513/105628887-0145a400-5e83-11eb-85bd-0b5d7fb34f8a.png">

**Comment by reustle** [comment]
Sorry for the delay here. Fortunately things have cleaned up quite a bit since then. I'm going to close this, as we try to simplify the site. Thank you for your suggestion.
