### ISSUE TITLE
Add breakdown of Positively Tested Population by age

### ISSUE THREAD

**Issue by czymra** [reustle/covid19japan#482]
The Toyokeizai visualizations are going to be discontinued, or at least stop being updated from February 1st https://toyokeizai.net/sp/visual/tko/covid19/en.html 

One of the most insightful visualizations there is "Tested Positive by Age" including deaths, serious conditions, hospitalized numbers and discharged numbers.
I think this helps understand what is actually happening in a more detailed manner. If this data is available here, I think it would be fantastic to add this.

<img width="460" alt="Screen Shot 2021-01-24 at 20 15 51" src="https://user-images.githubusercontent.com/12640513/105628965-84ff9080-5e83-11eb-82b2-dbc1eeb3adfb.png">

**Comment by reustle** [comment]
Thanks for the suggestion. If a PR is submitted with this feature, we'd be happy to review.
