### ISSUE TITLE
Bring back the dynamic city graphs with hover stats

### ISSUE THREAD

**Issue by bengarland** [reustle/covid19japan#485]
I would like to see the city graphs (e.g. Tokyo, Osaka...) come back, where I can hover my mouse over each day on the graph and see the stats such as number of new cases and deaths. It was there before, I want to say it disappeared during summer? The current design is a regression that makes it impossible to answer the question "How many new cases were there yesterday in Osaka? 3 days ago? 1 week ago?" The old graphs were also bigger and a lot easier to read.

**Comment by reustle** [comment]
Thanks for the suggestion, and sorry that we removed a feature that you found useful. I think we are going to keep moving in the direction of simplifying the site, instead of adding back more features. That said, if we see a PR submitted with the feature, we would be happy to review it. Thank you.
