### ISSUE TITLE
Bad data in "Recovered" and "Active Cases" graphs

### ISSUE THREAD

**Issue by a-ogilvie** [reustle/covid19japan#491]
It appears that the data displayed today (27th April 2021) is wildly incorrect.

| ![Screenshot 2021-04-27 at 23 06 01](https://user-images.githubusercontent.com/26034704/116255388-2660f000-a7ad-11eb-9891-7791e5ddfb92.png)  |  ![Screenshot 2021-04-27 at 23 03 41](https://user-images.githubusercontent.com/26034704/116255027-d124de80-a7ac-11eb-91a7-216ad63a5dad.png)  |
|---|---|

**Comment by liquidx** [comment]
Thanks for letting us know. I just fixed this bad data edit.
