### ISSUE TITLE
Outbreak Map—New color code for higher case numbers

### ISSUE THREAD

**Issue by laketiticaca** [reustle/covid19japan#493]
Now, the deep red color indicates 1,000 or more cases, although some prefectures currently have more than 5,000 active cases. Two adjacent prefectures have 21,000 and 1,000 cases respectively, but it seems that an additional color would be helpful to reflect the higher order of magnitude.

**Comment by reustle** [comment]
You're absolutely right that the colors needed to be updated. If it wasn't done already, we plan to move in a more 'per capita' color grading scale, to be more valuable. In that case, we shouldn't need any additional colors. Thanks for the suggestion!
