### ISSUE TITLE
Updates (mostly) missing since September 16

### ISSUE THREAD

**Issue by wbudd** [reustle/covid19japan#501]
I'm unlikely to be the first person to notice this, but I feel it should be useful to have an issue open here to track the status of the problem and progress toward resolving it.

So, yeah, what's up? (And what can I/anyone do to help fix this?)

**Comment by liquidx** [comment]
Thanks for reporting this. We also just noticed it and investigating it here:
https://github.com/reustle/covid19japan-data/issues/92

Looks like the process that updates the data hit a memory limit and started failing.

**Comment by liquidx** [comment]
This should be fixed now, we've increased the memory limit on the node process so it should continue to work for now.
