### ISSUE TITLE
Per-region "Active" count seems to have stopped updating

### ISSUE THREAD

**Issue by amitlan** [reustle/covid19japan#503]
Hello developers, thanks for your work on this.

It seems to me that per-region Active counts are not updating itself in the last few days.  The total count shown at the top of page is 16,068 as of 2021-10-08 evening, though Kanto shows 14,844, Kansai 13,806, and so on.

**Comment by liquidx** [comment]
Thanks for reporting this. Looks like one of our automated processes failed last week and none of the recovery numbers got updated. I've fixed it now and the active numbers for Kanto are now calculated to be 9702. for 10-08
