### ISSUE TITLE
Chart Left Padding needs bumped

### ISSUE THREAD

**Issue by FraserTooth** [reustle/covid19japan#510]
In a somewhat unfortunate turn of events - there are now so many cases that the first digit bleeds off the end of the chart
<img width="634" alt="image" src="https://user-images.githubusercontent.com/25011388/180677875-07e6a76f-ba91-4eff-a80b-8e9f051c2746.png">

I already have a fix locally (just bumping the left padding up to `55`) can make a branch and PR if you're happy to make this change 👍

**Comment by FraserTooth** [comment]
Other fix options could be:
- Angling the text
- Making the text smaller
- Shortening the formal (e.g. `1,000,000` -> `1 mill`)

**Comment by liquidx** [comment]
Thanks this make sense, we probably should make the padding a little bigger, seems like a reasonable fix.

**Comment by liquidx** [comment]
Should be fixed now, thanks for your report and suggestion!
