### ISSUE TITLE
Add data and information for Diamond Princess

### ISSUE THREAD

**Issue by plusfuture** [reustle/covid19japan#61]
@reustle - Thanks for making this, it's been really helpful for me personally and I'm sure many others

The site should also add numbers for Diamond Princess. Additionally, site visitors should know that the Japanese government let people off without properly testing, and that there are still more people on the ship who are sick who will be let off later.

To avoid creating multiple issues I've listed other ideas below:
1. Add to the Helpful Links section basic info like "the best method of prevention is hand washing, this is how to properly wash your hands," "does wearing a mask actually help," "what is the mild/severe/critical case ratio," etc. with links embedded in the information. 
2. Describe not only the officially published numbers but the actual situation, e.g. that the Japanese government is under-testing compared to Italy/SK and that's why the numbers are lower, that even if you get sick there's no treatment, and to go to the hospital if your fever goes over 37.5C or you have difficulty breathing. All of this should be sourced and linked to as well.

I'm happy to make pull requests as well, please let me know.

**Comment by reustle** [comment]
I think it's soon time we start including whatever cruise passengers remain in Japan into the main data, as it seems other sites are doing the same.

**Comment by liquidx** [comment]
There's a difference between the Cruise Passengers that were infected onboard, and the ones that tested negative onboard, but later tested positive.

The former (tested positive onboard), we could add them as just a number in a separate sheet that we pull in. This one is updated by MHLW. 

The latter (tested negative onboard, but later positive), they're accounted for in the prefectures already.

**Comment by liquidx** [comment]
Closing this older issue. We now have a row in the prefecture table that lists the diamond princess numbers in case people needed to know.
