### ISSUE TITLE
data.json looks from a different time zone

### ISSUE THREAD

**Issue by ggouaillardet** [reustle/covid19japan#69]
Right now (2020/3/3 22:34 JST), https://covid19japan.s3.ap-northeast-1.amazonaws.com/data.json ends with

```
{"date":"2020-03-01","confirmed":"257","recovered":"41","deceased":"6","critical":"20","tested":"2339"},{"date":"2020-03-02","confirmed":"283","recovered":"42","deceased":"6","critical":"23","tested":"2517"}],"updated":[{"lastupdated":"Mar 3 2020, 21:12 JST"}]}
```

the live patient database contains 283 confirmed cases, but 6 were announced on 2020/3/3.
Consequently, the total confirmed cases on 2020/3/2 is 277, and the difference should be 6
(but the website lists 283 confirmed cases on 2020/3/2 and the difference is 26)

A possible explanation is `data.json` was generated on a different timezone (and I do not know which one). I would assume most users are based in Japan and would rather have `data.json` in JST instead of an other (and unknown to me) timezone.

Please keep up the good work, this is a very valuable resource to me.

**Comment by ggouaillardet** [comment]
A few minutes later (22:59 JST), `data.json` looks much better to me.

```
{"date":"2020-03-01","confirmed":"257","recovered":"41","deceased":"6","critical":"20","tested":"2339"},{"date":"2020-03-02","confirmed":"276","recovered":"42","deceased":"6","critical":"23","tested":"2517"},{"date":"2020-03-03","confirmed":"283","recovered":"42","deceased":"6","critical":"23","tested":"2517"}],"updated":[{"lastupdated":"Mar 3 2020, 21:12 JST"}]}
```

I noted the difference in confirmed cases is 7 (instead of 6) and I believe the root cause is it is based on the `Date Added` column of the `live patient database` instead of the `Date Announced` column. This is a very minor thing to me.
One more minor thing, I am not a native English speaker, but should it be `patient live database` instead of `live patient database` ?

**Comment by reustle** [comment]
Sorry, there was human error on the spreadsheet and an entry for 3/3 wasn't added on the "sum by day" sheet. I've added one and that's why you saw the correction, while the increases for the day aren't yet correct.

I agree `live patient database` sounds a bit weird, but I still believe it's more correct? "live" describes the patient database.

Thanks for the heads up
