### ISSUE TITLE
Japanese translation (first phase)

### ISSUE THREAD

**Issue by khasunuma** [reustle/covid19japan#7]
@reustle I've quickly translate `index.html` to Japanese and save it as `index_ja.html` in my repository forked from your original. I'd like to contribute the site as a Japanese person.

I'll send you the pull request after a few minutes. Since the map doesn't work in my local environment, Could you please modify to work well if you would accept the pull request.

I want to translate prefectures' name in the "Prefecture Data" table, however, it's difficult to translate quickly for now. It's my challenge.

**Comment by reustle** [comment]
For those checking on this issue, I am replying on the pull request
