### ISSUE TITLE
Implement Babel

### ISSUE THREAD

**Issue by coliff** [reustle/covid19japan#70]
I noticed that the page doesn't load on Internet Explorer 11 (which still has a fairly large marketshare in Japan). Not sure what the issue is, but I wonder if Polyfill.io could help fix?
`<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js"></script>`

![image](https://user-images.githubusercontent.com/1212885/75793372-9dba1000-5db2-11ea-99ac-1d792e2ef96e.png)

**Comment by reustle** [comment]
Thank you for bringing this up. Yes, we'd like to support IE11 moving forward. Since we're now using webpack, we can solve these issues using Babel: https://babeljs.io/

**Comment by coliff** [comment]
seems to be working now. 👍 

![image](https://user-images.githubusercontent.com/1212885/77406390-e97f3880-6df7-11ea-854f-073320825ead.png)

**Comment by liquidx** [comment]
Oh awesome! Thanks for confirming.
