### ISSUE TITLE
How/where is data from the spreadsheet converted into the data.json?

### ISSUE THREAD

**Issue by brettwooldridge** [reustle/covid19japan#74]
Looking at the code in the repository, I do not find code that generates the ``data.json`` from the Google Doc spreadsheet.  Am I missing it?

**Comment by brettwooldridge** [comment]
nvm.  I get it.  I was interesting in parsing the data in the *Patient Data* tab, and altering the Prefecture Table to something like:
```
Hokkaido                    83             -               3
  Sapporo                   36             1               2
  Okhotsk                   10             -               0
Kanagawa                    31             -               1
  Sagamihara                14             -               1
  Atsugi                     1             -               0
...
```
With better row shading differentiation than can be expressed here.

**Comment by reustle** [comment]
Hey Brett! Sorry I didn't see this sooner, and thanks for taking the time to contribute. This sounds similar to https://github.com/reustle/covid19japan/issues/20 which we'd love to see. We may be modifying the source data soon ( #65 ) so this may change very soon. Would you plan to do this calculation in the current node code that generates the cache json?

Thanks again

**Comment by reustle** [comment]
Closing, feel free to reopen

**Comment by brettwooldridge** [comment]
@reustle How far off is #65 ?  Maybe better to add the functionality once the backend is refactored...

**Comment by reustle** [comment]
I believe @liquidx has already done some work regarding parsing the patient data table directly on the frontend, which we are starting to agree is the right way to move forward. I'll let him chime in regarding his progress, but would happy to have you help jump in and reduce our dependency on the other sheets that contain formulas.

Thank you!

**Comment by brettwooldridge** [comment]
Ok, thanks.  1:30am here in Tokyo, but hopefully tomorrow night I can start taking a look at implementation.

**Comment by liquidx** [comment]
We don't have a JSON file of the Patient Data tab, but I have been using drive-db to fetch this live from the spreadsheet. But maybe it would be easier if we did do a regular check in of the json file into a github repo?

Here's an example of trying to break out the city data in your example:
https://github.com/liquidx/covid19japan/tree/viz/src/explore.js
(Sorry, ignore my attempt to use MDC tables to make it pretty)

Live example:
https://covid2019-test.firebaseapp.com/explore.html

Suggestions on how this could be done better, or even building upon that would be awesome.

**Comment by reustle** [comment]
> We don't have a JSON file of the Patient Data tab

We could easily alter the cache script to include it, or to create a separate `patientData.json` for this purpose.

**Comment by liquidx** [comment]
You should be able to process the raw patient data (and look through how the daily/prefecture summaries are created) here:
https://github.com/reustle/covid19japan-data

Note that in the prefecture summary examples I've now outputed a per-city count which you can use directly for your idea!
