### ISSUE TITLE
Apply Mapbox Geographic Bounds for interactive map

### ISSUE THREAD

**Issue by psylum** [reustle/covid19japan#79]
Hey @reustle, just a minor design suggestion. The interactive Mapbox map has a good minimum zoom, but you could also apply a `maxBounds` to the map, so it's impossible to accidentally scroll the map far away from the general region of Japan itself when zooming or scrolling around.

**Comment by reustle** [comment]
Hey @psylum thanks for reaching out. We've actually already set `maxBounds` here https://github.com/reustle/covid19japan/blob/master/static/main.js#L112-L115

Which device are you using? Maybe there is a feature compatibility issue, as it appears to be working fine for me on desktop and mobile. Thanks!

**Comment by psylum** [comment]
ah, i just tried it again and found the bounds. i'm using Safari on a desktop, but i guess i was zoomed in one level and ended up well out into the ocean. i guess i just expected the bounds to be in tighter than they currently are.
