### ISSUE TITLE
Tests to Trend Line

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#80]
Add the number of tests performed to the trend chart, or its own chart

**Comment by reustle** [comment]
This is done but currently hidden in code with a single commented out line. It may make more sense as a bar chart w/ increase by day, instead of a total sum.

**Comment by reustle** [comment]
![image](https://user-images.githubusercontent.com/304560/77913880-002dff80-72d0-11ea-8434-d9c7ac5a1773.png)

Blue = tested positive
red = number of tests

unsure of the source

**Comment by AdamT** [comment]
Your solution above looks good but if you're unsure perhaps making a tests per day look like "New Cases By Day"? (I don't so much care about how many tested positive, since there's a chart for that already), just some thoughts

**Comment by ymilly** [comment]
Seems this hasn't been touched for a couple weeks. I think getting tests conducted per day it really important to add meaning to positives/day.
Is it the 'unknown data source' that is holding this up?

**Comment by buttobase** [comment]
![Screenshot_20200420-224137](https://user-images.githubusercontent.com/1122479/79758403-51be2d00-8358-11ea-947b-a4883b426343.png)
My local prefecture Hyogo shares this data

https://web.pref.hyogo.lg.jp/kk03/200129.html#kensa_new

And obviously tests/results appear in lockstep when you eyeball it... Definitely a great indicator!

**Comment by reustle** [comment]
Note @liquidx @l15n I've gotten so many direct requests for this graph that I think it might be worth a bit of extra CPU load for the time being. Bumping this issue up.

**Comment by reustle** [comment]
Added
