### ISSUE TITLE
Travel Bans

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#84]
1. Add a list of countries banned from travel into Japan (or need quarantine)
2. Add a list of countries which people coming from Japan are banned from entering

i.e. https://twitter.com/motokorich/status/1240248532377858050
> parts of Spain, Switzerland, and all of Iceland, plus mandating 14-day quarantines for travelers from 38 countries, inducing all Europe, UK, Ireland and Egypt.

**Update**: V1 is now launched on the site, we just need to update the data

---

<img width="696" alt="image" src="https://user-images.githubusercontent.com/304560/77826465-e4511f00-7152-11ea-8544-6c45f8e60ad0.png">

**Comment by nateberkopec** [comment]
Relevant 

https://www.iatatravelcentre.com/international-travel-document-news/1580226297.htm

https://www.japan.travel/en/coronavirus/

**Comment by ann-kilzer** [comment]
These are helpful sources. Wondering what's the best way to summarize this, as it's a long list. Could divide into a few categories, like "No entry", "Must Quarantine", "Visa on arrival suspended." What do you think? I have a WIP branch I can share soon.

**Comment by reustle** [comment]
Another source: https://www.japantimes.co.jp/news/2020/03/19/national/abe-imposes-14-day-quarantine-japan-arrivals-several-countries-europe/#.XnLxsS2B2gQ

Yeah, I think a few simple lists would work, like below. Maybe each country on the list could be a link to the source of that info?

---

### Traveling Into Japan

Below are the travel restrictions that have been put in place regarding traveling to / from Japan. Click on the country link for more details on the restrictions.

**Banned From Entering Japan**: Italy, China, ...

**Existing Visa Required**: Spain, ...

**Other Limitations**: Greece (details), Germany (details), ...

### Traveling Out Of Japan

*Similar lists here, if any*

**Comment by l15n** [comment]
Here are the primary sources

- For denial of landing, via the MoJ http://www.moj.go.jp/hisho/kouhou/20200131comment.html
    - Announcement: http://www.moj.go.jp/nyuukokukanri/kouhou/nyuukokukanri01_00128.html
    - English: http://www.moj.go.jp/content/001316999.pdf
- For 14-day quarantine restrictions, its the MHLW:
    - Announcement: https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000121431_00098.html


There's also numbers on

**Comment by l15n** [comment]
I've only noticed two actual categories:
* Banned from entering Japan (denial of entry): travellers who have stayed at specific regions within the last 14 days of China, Korea, Iran, Italy, San Marino, Switzerland, Spain, Iceland.
* Requested to self-quarantine (starting 3/21): 
    * travellers coming from Europe, Egypt, Iran (in addition to China, Korea, where these restrictions already apply)
    * travellers coming from other destinations who have stayed in the above countries in the 14 days prior to arrival in Japan.

**Comment by reustle** [comment]
@ann-kilzer 

Thank you for your work on the PR! Do you think we could simplify it down to something like what was mentioned here? I feel trying to keep up with a list of every region (sub-country) is going to be quite time consuming, we should instead just direct the users to the proper source on a country level. Here's an updated suggestion on what this could look like, including flag emojis to help w/ quick scanning. Thanks!

---

### Traveling Into Japan

Below are the travel restrictions that have been put in place regarding traveling to / from Japan. Click on the country link for more details on the restrictions.

**Banned From Entering Japan**: [🇮🇹 Italy](#), [🇨🇳 China](#), ...

**Existing Visa Required**: 🇪🇸 Spain, ...

**14-day Self-Quarantine Required**: 🇪🇸 Spain, ...

**Other Limitations**: 🇬🇷 Greece (details), 🇩🇪 Germany (details), ...

### Traveling Out Of Japan

*Similar lists here, if any. This would be a list of countries who have imposed travel restrictions on people who are coming from Japan*

**Comment by reustle** [comment]
This has been deployed, now we need to make sure the info is correct / complete.

**Comment by reustle** [comment]
https://english.kyodonews.net/news/2020/04/5176f48c552d-japan-to-expand-entry-ban-to-73-countries-regions-amid-virus-spread.html
