### ISSUE TITLE
Add Prefecture Breakdown of Active and Recovered Cases to Table

### ISSUE THREAD

**Issue by zaldabus** [reustle/covid19japan#91]
@reustle 

As time progresses the number of total cases versus active cases will likely progressively diverge, making the number of active cases a much more relevant metric for how day to day behavior should change. A similar argument could be made for recovered cases. 

Right now with the given setup the page only displays total active and recovered cases. However, cases by prefecture would be much more helpful information. 

The page currently has a table which could easily be extended to include this information. 

If pointed in the direction of where the page is currently getting its data, I could probably add this in pretty quickly. This is assuming we also have the relevant data at a prefectural level.

**Comment by liquidx** [comment]
Good idea, but we don't have the per-prefecture recovered data that's reliable. The Ministry of Health reports an overall recovery number but only a handful of prefectures report their recovery numbers. (Saitama is one of them)

**Comment by zaldabus** [comment]
Definitely makes sense to only post information that’s reliable. 

Has a in-depth search of prefecture available information been performed recently? If not, I can spend some time looking into it. Otherwise, mine as well close this issue, or maybe put it on hold for a few weeks and do a recheck later to see if prefectures have gotten more on top of their own records.

**Comment by reustle** [comment]
Thanks @zaldabus  - BTW we just deployed an updated chart which includes the trend line for Active cases.

Just to make sure I understand, is your suggestion to add an `Active` column to the prefectures table?

![image](https://user-images.githubusercontent.com/304560/77434820-ca4ad000-6e24-11ea-8023-a4576fc194ea.png)

**Comment by zaldabus** [comment]
Nice, love the recent updates. 

I’d say the spirit of what I was hoping for was to provide a clearer picture of relevant data at the prefectural level, which recent updates address. 

I like the direction of proposed changes @l15n has been making in #109. Given that what I was hoping for has been addressed, I’m gonna close this issue in favor of work focused on that issue.
