### ISSUE TITLE
Improved localization using json files

### ISSUE THREAD

**Issue by ann-kilzer** [reustle/covid19japan#93]
I notice that localization is inline in the code. It might help to switch to a framework that allows json files for easier translation -- i.e., translators can focus on the content and don't need to understand javascript / html.

Suggestions for code frameworks:
- https://github.com/jeresig/i18n-node-2
- https://github.com/AGROSICA/node-localize

Suggestions for translation tools:
- https://lokalise.com/ (use the free trial to kickstart things)

I have friends that can help with Japanese translation.

What do you think, @reustle?

Related: #87

**Comment by reustle** [comment]
Nice idea! How would the switching on the frontend work? Would some javascript function be called which then goes out and finds all the text variables and swaps them? How about the initial HTML of the page, I'm guessing it would be empty (no text)?

**Comment by mertd** [comment]
I have made good experiences with [i18next](https://github.com/i18next/i18next); it's very portable.

@reustle Yes, the translations would be filled in with JavaScript; the framework (at least in case of i18next) can detect the browser language but manual switching is, of course, possible. The initial HTML can be pre-filled with a default text, though I would advise against it unless we actually have issues with the page rendering slowly.

**Comment by mertd** [comment]
I took the liberty to start working on this in #124

**Comment by ann-kilzer** [comment]
I set up i18n at my company (we use Vue.js) and it's really slick. It even gives us the option of adding more languages (Chinese, Korean, etc.) Thanks for taking the torch @mertd and happy to refer some more bilingual friends this way if any help is needed.

**Comment by l15n** [comment]
I just found the translation set up for the Tokyo setup

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/TRANSLATION.md

They're using Transifex.
